var:
  lang: en-US
  db-name: wf
  db-user: ${MYSQL_USER:root}
  db-password: ${MYSQL_PASSWORD:123456}
  ft-path: /opt/websites_workspace/wf/ft-index
  upload-disabled: false
  upload-path: /opt/websites_workspace/wf/upload

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server:
  port: 9090
  address: 127.0.0.1
  sessionTimeout: 30
  contextPath: /

  error:
    whitelabel:
      enabled: false
  
# APPLICATION
application:
  name: @project.name@
  version: @project.version@
  short-name: @project.shortName@
  build-number: @project.buildNumber@
  default-lang: ${var.lang}
  upload-disabled: ${var.upload-disabled}
  upload-path: ${var.upload-path}
  full-text-index-path: ${var.ft-path}
  rename-upload-file: false
  mail-sender: zb@bndy.net
  allowed-origins: http://bndy.net, http://localhost:5500
  default-user-avatar: /static/assets/img/me.png
  admin-skin: skin-blue-light
  admin-role: Admin, The system administrator who has full all privileges.

# LOGGING  
logging:
  file: /opt/websites_workspace/wf/logs/app.log
  config: 
  level:
    org.springframework.web: DEBUG
    hibernate: DEBUG

# BANNER  
banner:
  charset: UTF-8 # Banner file encoding.  
  location: classpath:banner.txt # Banner file location.  
  image:
    location: classpath:banner.gif # Banner image file location (jpg/png can also be used).  
    width:  # Width of the banner image in chars (default 76)  
    height:  # Height of the banner image in chars (default based on image height)  
    margin:  # Left hand image margin in chars (default 2)  
    invert:  # If images should be inverted for dark terminal themes (default false)  

spring:
  #APPLICATION SETTINGS (SpringApplication) 
#  main:
#    banner-mode: console # Mode used to display the banner when the application runs.  
#    sources: # Sources (class name, package name or XML resource location) to include in the ApplicationContext.  
#    web-environment: # Run the application in a web environment (auto-detected by default).

  ftsi:
    analyzer: org.apache.lucene.analysis.standard.StandardAnalyzer
    data-path: ${application.full-text-index-path}
    highlight-pre-tag: <b class="highlight">
    highlight-post-tag: </b>
    highlight-fragment-size: 300

  # Email (MailProperties)  
  mail:
    default-encoding: UTF-8 # Default MimeMessage encoding.  
    host: xxx.bndy.net # SMTP server host. For instance `smtp.example.com`  
    #jndi-name: # Session JNDI name. When set, takes precedence to others mail settings.  
    password: xxx # Login password of the SMTP server.  
    port: 21 # SMTP server port.  
    protocol: smtp # Protocol used by the SMTP server.  
    test-connection: false # Test that the mail server is available on startup.  
    username: xxx # Login user of the SMTP server. 
    #properties.*: # Additional JavaMail session properties.  
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        starttls.required: false

  # Upload
  http:
    multipart:
      max-file-size: -1 #1024KB
      max-request-size: -1  #1024KB

  # MVC
  mvc:
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true
    
  # RESOURCES
  resources:
    add-mappings: true
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

  # DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)  
  datasource:
    url: jdbc:mysql://localhost:3306/${var.db-name}?useSSL=false&characterEncoding=utf8
    username: ${var.db-user}
    password: ${var.db-password}
    driver-class: com.mysql.jdbc.Driver
    testWhileIdle: true 
    validationQuery: SELECT 1
    
  # JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: net.bndy.wf.config.DatabaseImplicitNamingStrategy
        # If not specified, default org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        # which will add underscores to names and convert to lowercase
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl   # This will use the logical names for database
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    
#    
#  data:
#    # MONGODB (MongoProperties)  
#    mongodb:
#      host: # the db host  
#      port: 27017 # the connection port (defaults to 27107)  
#      uri: mongodb://localhost/test # connection URL  
#    mongo:
#      repositories:
#        enabled: true # if spring data repository support is enabled 
#        
#    # SOLR (SolrProperties})  
#    solr:
#      host: http://127.0.0.1:8983/solr  
#      zkHost: 
#      repositories:
#        enabled: true # if spring data repository support is enabled 
#    
#  # REDIS (RedisProperties)  
#  redis:
#    host: localhost # server host  
#    password: # server password  
#    port: 6379 # connection port  
#    pool:
#      max-idle: 8 # pool settings ...  
#      min-idle: 0  
#      max-active: 8  
#      max-wait: -1  
      
  # THYMELEAF (ThymeleafAutoConfiguration)  
  thymeleaf:
    prefix: classpath:/templates/  
    suffix: .html  
    mode: LEGACYHTML5   #HTML5  
    encoding: UTF-8  
    content-type: text/html  
    cache: false

  # i18n
  messages:
    basename: i18n/messages
    
  # SPRING CACHE (CacheProperties)
  cache:
    #type:  # Cache type, auto-detected according to the environment by default.
    #cache-names: # Comma-separated list of cache names to create if supported by the underlying cache manager.
    #caffeine.spec: # The spec to use to create caches. Check CaffeineSpec for more details on the spec format.
    jcache:
      config: classpath:config/ehcache.xml
    #jcache.provider: # Fully qualified name of the CachingProvider implementation to use to retrieve the JSR-107 compliant cache manager. Only needed if more than one JSR-107 implementation is available on the classpath.

security:
  oauth2:
    # SECURITY OAUTH2 CLIENT (OAuth2ClientProperties)
    client:
      #client-id: # OAuth2 client id.
      #client-secret: # OAuth2 client secret. A random secret is generated by default

    # SECURITY OAUTH2 RESOURCES (ResourceServerProperties)
    resource:
      filter-order: 3 # The order of the filter chain used to authenticate tokens.

    # SECURITY OAUTH2 SSO (OAuth2SsoProperties)
    sso:
      #filter-order: 2 # Filter order to apply if not providing an explicit WebSecurityConfigurerAdapter
      #login-path: /sso/login # Path to the login page, i.e. the one that triggers the redirect to the OAuth2 Authorization Server
